# Generated by Django 5.0.4 on 2025-03-07 10:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='John Doe', max_length=40)),
                ('email', models.CharField(default='john@email.com', max_length=40)),
                ('phone', models.CharField(default='+1 234567890', max_length=40)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='CSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('description', models.CharField(default='Description', max_length=160)),
                ('c_filter', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Case Study Categories',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='How helps?', max_length=100)),
                ('answer', models.CharField(blank=True, max_length=550, null=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage FAQs',
            },
        ),
        migrations.CreateModel(
            name='GetQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='john@email.com', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Quotation Requests',
            },
        ),
        migrations.CreateModel(
            name='SEOHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SEO title', max_length=80)),
                ('description', models.CharField(default='SEO description', max_length=160)),
                ('canonical', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Metadata',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_h1', models.CharField(max_length=60)),
                ('short_description', models.CharField(max_length=550)),
                ('highlight_points', models.JSONField(default=list)),
                ('cover', models.ImageField(default='service.jpg', upload_to='services')),
                ('heading_h2_1', models.CharField(max_length=150)),
                ('paragraph_1', models.TextField(max_length=1000)),
                ('technical_points', models.JSONField(default=list)),
                ('heading_h3', models.CharField(max_length=150)),
                ('paragraph_1_1', models.TextField(max_length=1000)),
                ('image_1', models.ImageField(default='service-1.jpg', upload_to='services')),
                ('image_2', models.ImageField(default='service-2.jpg', upload_to='services')),
                ('heading_h2_2', models.CharField(max_length=150)),
                ('paragraph_2', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Logo', max_length=70)),
                ('logo', models.ImageField(default='tech-logo.png', upload_to='tech-logos')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=40)),
                ('profession', models.CharField(default='Engineer', max_length=40)),
                ('message', models.CharField(blank=True, max_length=600, null=True)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Company', max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=160, null=True)),
                ('image', models.ImageField(default='case-study.jpg', upload_to='case-studies')),
                ('link', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cscategory')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.service')),
            ],
        ),
    ]
