# Generated by Django 5.0.4 on 2025-03-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='highlight_points',
        ),
    ]
