# Generated by Django 5.0.4 on 2024-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_casestudy_category_alter_casestudy_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
