# Generated by Django 5.0.4 on 2025-03-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_highlight_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefaq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='technical_points',
        ),
        migrations.CreateModel(
            name='ServiceHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_1', models.CharField(max_length=200)),
                ('highlight_2', models.CharField(max_length=200)),
                ('highlight_3', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_highlights', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
        migrations.CreateModel(
            name='ServiceTechnicalHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_1', models.CharField(max_length=200)),
                ('technical_2', models.CharField(max_length=200)),
                ('technical_3', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_highlights', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Tech Highlights',
            },
        ),
    ]
