# Generated by Django 5.0.4 on 2024-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_getquote_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getquote',
            name='email',
            field=models.CharField(default='john@email.com', max_length=40),
        ),
    ]
