# Generated by Django 5.0.4 on 2025-03-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicefaq_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehighlights',
            old_name='highlight_1',
            new_name='highlight',
        ),
        migrations.RenameField(
            model_name='servicetechnicalhighlights',
            old_name='technical_1',
            new_name='technical',
        ),
        migrations.RemoveField(
            model_name='servicehighlights',
            name='highlight_2',
        ),
        migrations.RemoveField(
            model_name='servicehighlights',
            name='highlight_3',
        ),
        migrations.RemoveField(
            model_name='servicetechnicalhighlights',
            name='technical_2',
        ),
        migrations.RemoveField(
            model_name='servicetechnicalhighlights',
            name='technical_3',
        ),
    ]
