# Generated by Django 5.0.4 on 2025-03-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_highlight_1_servicehighlights_highlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_highlight', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Highlights',
            },
        ),
        migrations.CreateModel(
            name='ServiceTechnicalHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_highlight', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Tech Highlights',
            },
        ),
    ]
