# Generated by Django 5.0.4 on 2024-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_getquote_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSMangalore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='How helps?', max_length=100)),
                ('answer', models.CharField(blank=True, max_length=550, null=True)),
            ],
            options={
                'verbose_name_plural': 'FAQs for SEO in Mangalore',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Homepage FAQs'},
        ),
    ]
