# Generated by Django 5.0.4 on 2024-05-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faqsmangalore_alter_faq_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQSMangalore',
        ),
    ]
