# Generated by Django 5.0.4 on 2025-03-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicehighlight_servicetechnicalhighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetechnicalhighlights',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceHighlights',
        ),
        migrations.DeleteModel(
            name='ServiceTechnicalHighlights',
        ),
    ]
