# Generated by Django 5.0.4 on 2025-03-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_servicetechnicalhighlights_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_h2', models.CharField(max_length=150)),
                ('paragraph_1', models.TextField(max_length=1000)),
                ('heading_h3', models.CharField(max_length=150)),
                ('paragraph_1_1', models.TextField(max_length=1000)),
                ('image_1', models.ImageField(default='service-1.jpg', upload_to='services')),
                ('image_2', models.ImageField(default='service-2.jpg', upload_to='services')),
            ],
            options={
                'verbose_name_plural': 'Service Section 1',
            },
        ),
        migrations.CreateModel(
            name='ServiceSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_h2', models.CharField(max_length=150)),
                ('paragraph_1', models.TextField(max_length=1000)),
                ('image_1', models.ImageField(default='service-3.jpg', upload_to='services')),
            ],
            options={
                'verbose_name_plural': 'Service Section 2',
            },
        ),
    ]
