# Generated by Django 5.0.4 on 2025-03-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicesection1_servicesection2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSection1',
        ),
        migrations.DeleteModel(
            name='ServiceSection2',
        ),
        migrations.AlterModelOptions(
            name='servicehighlight',
            options={'verbose_name_plural': 'Service Section 1'},
        ),
        migrations.AlterModelOptions(
            name='servicetechnicalhighlight',
            options={'verbose_name_plural': 'Service Section 2'},
        ),
    ]
