# Generated by Django 5.0.4 on 2025-03-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_servicesection1_delete_servicesection2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehighlight',
            options={'verbose_name_plural': 'Highlights'},
        ),
        migrations.AlterModelOptions(
            name='servicetechnicalhighlight',
            options={'verbose_name_plural': 'Tech Highlights'},
        ),
        migrations.CreateModel(
            name='ServiceSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_h2', models.CharField(max_length=150)),
                ('paragraph_1', models.TextField(max_length=1000)),
                ('heading_h3', models.CharField(max_length=150)),
                ('paragraph_1_1', models.TextField(max_length=1000)),
                ('image_1', models.ImageField(default='service-1.jpg', upload_to='services')),
                ('image_2', models.ImageField(default='service-2.jpg', upload_to='services')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section_1', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Service Section 1',
            },
        ),
        migrations.CreateModel(
            name='ServiceSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_h2', models.CharField(max_length=150)),
                ('paragraph_1', models.TextField(max_length=1000)),
                ('image_1', models.ImageField(default='service-3.jpg', upload_to='services')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section_2', to='core.service')),
            ],
            options={
                'verbose_name_plural': 'Service Section 2',
            },
        ),
    ]
