# Generated by Django 5.0.4 on 2025-03-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_servicehighlight_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='heading_h2_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='heading_h2_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='heading_h3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='paragraph_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='paragraph_1_1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='paragraph_2',
        ),
    ]
