# Generated by Django 5.0.4 on 2025-03-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_service_heading_h2_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='short_description',
            new_name='description',
        ),
    ]
