# Generated by Django 5.0.4 on 2025-03-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_short_description_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesection1',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_section_1', to='core.service'),
        ),
        migrations.AlterField(
            model_name='servicesection2',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_section_2', to='core.service'),
        ),
    ]
