# Generated by Django 5.0.4 on 2025-03-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_servicesection1_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefaq',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
    ]
