# Generated by Django 5.0.4 on 2025-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_servicefaq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=40)),
                ('phone', models.CharField(default='+1 234567890', max_length=40)),
                ('message', models.TextField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Page Leads',
            },
        ),
    ]
