# Generated by Django 5.0.4 on 2025-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_servicepagelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Service', max_length=40),
        ),
    ]
