# Generated by Django 5.0.4 on 2025-03-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
