# Generated by Django 5.0.4 on 2025-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='name',
            field=models.CharField(default='Company', max_length=40),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(default='Company Case Study', max_length=40),
        ),
    ]
